language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
before_install:
  - chmod +x gradlew
after_success:
  - ls -al
script:
  - ./gradlew assemble
env:
branches:
  only:
    - master
notifications:
  email: false
sudo: false

