language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
before_install:
  - chmod +x gradlew
after_success:
  - ls -al
script:
  - ./gradlew assemble
env:
branches:
  only:
    - master
notifications:
  email: false
sudo: false
deploy:
  provider: releases
  api_key: 009e760502e923451e32fec28717e3f1c205fcc5
  file: logger-sample/build/outputs/apk/logger-sample-debug.apk
  skip_cleanup: true
  on:
    tags: true
