language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
before_install:
  - chmod +x gradlew
  - chmod +x .buildscript/maven_push.sh
after_success:
  - echo $bintrayKey
script:
  - .buildscript/maven_push.sh $bintrayUser $bintrayKey
env:
notifications:
  email: false
sudo: false
deploy:
  - provider: releases
    api_key:
      secure: "Z1RRyYiCejQ8zv8e4ZNTDyMVdfLbmSQQOFljIzzTE/5lv9+wATlItXeUerJFUXJfc50OZqF1WviGvA4Zt12UhOSMMJn7m7BYyNXKZaFF1QutTk4gMZTmDqW7QTW17GeuvpDcMfksAstIVO9Txk0D8BxE6xZYdTq51P84F+M3K9Z3oPSQ9eE64G/y39/7EqziqY8oyM7eJSqc2lQ+7o/Do++RJpzrqoagy0GDLJwnAWPZ4pK+wG+0R1cK3jTTfIjG42CUanW5GwaZQ2EVRo0dR4/1glpXBfLQZb9Jtm5sJwEs81NGpN9Y51U8DKBBfZHmiFND0dZRN8OeYcQGZjs9cAFoVDNvCX3EwL/BlNiw2k3a0j3QCx8KKjBGHcCoqzl7CHY+vPd72vB4vzMMhJLLwssJmqFlb2GiX+/94EKIxJuWsnspeTSZmNuSC7fK155CjaWUvONaENj/1BnJ34hHNC/vkRH+UMjBBSNY/oxo3XoLjBsydqapWhmHnK9r43kBfpFuQxCitsyOeldPC0jemHU+6xqZBX41IF2rIYuL0xKRHap7GpVhrM2ResJ0GDuslNdxSkL7+2qFvdxTzCDKf/4VMSai5cDatlU0L8SDZhS+3rktqQr6xJA2JEJa6pWippe3Xd71opF3jfiFZBFNue3eyzWPBZXEdWvtM4Jqbps="
    file:
      - "logger-sample/build/outputs/apk/logger-sample-debug.apk"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
    overwrite: true
